# GitHub Pages configuration for 7pace MCP Server
title: "7pace MCP - AI-Powered Time Tracking"
description: "Track time naturally with Claude AI. Zero context switching, 87% faster than traditional tools."
url: "https://turnono.github.io"
baseurl: "/7pace-mcp-server"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# SEO settings
author: "Abdullah Abrahams"
twitter:
  username: turnono
  card: summary_large_image

# Social media
social:
  name: "7pace MCP"
  links:
    - https://github.com/turnono/7pace-mcp-server
    - https://twitter.com/turnono

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - src/
  - dist/
  - .env
  - .env.example
  - "*.test.js"
  - "test-*.js"
