# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts && npm run build

ENV NODE_ENV=production
ENV SEVENPACE_ORGANIZATION=example
ENV SEVENPACE_TOKEN=test-token-replace-with-real-token

CMD ["node", "dist/index.js"]
